"""empty message

Revision ID: 392f27fcca90
Revises: 4ea8abbb8c3e
Create Date: 2026-07-07 20:52:46.471007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392f27fcca90'
down_revision = '4ea8abbb8c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Integer(), nullable=False),
    sa.Column('visto', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tipo')
    )
    op.create_table('publicacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_seguidor', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_seguidor'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicacion.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('seguidor')
    op.drop_table('publicacion')
    op.drop_table('notificacion')
    # ### end Alembic commands ###
