"""empty message

Revision ID: 4ea8abbb8c3e
Revises: b0cb8001cc39
Create Date: 2026-07-07 20:27:33.235022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea8abbb8c3e'
down_revision = 'b0cb8001cc39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_empresa', sa.Integer(), nullable=False),
                    sa.Column('id_empleado', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(length=120), nullable=False),
                    sa.Column('direccion', sa.String(
                        length=120), nullable=False),
                    sa.Column('telefono', sa.Integer(), nullable=False),
                    sa.Column('fecha_incorporación',
                              sa.Integer(), nullable=False),
                    sa.Column('función', sa.String(
                        length=120), nullable=False),
                    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_empleado')
                    )
    op.create_table('programador',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_empresa', sa.Integer(), nullable=False),
                    sa.Column('id_empleado', sa.Integer(), nullable=False),
                    sa.Column('nombre', sa.String(length=120), nullable=False),
                    sa.Column('direccion', sa.String(
                        length=120), nullable=False),
                    sa.Column('telefono', sa.Integer(), nullable=False),
                    sa.Column('fecha_incorporación',
                              sa.Integer(), nullable=False),
                    sa.Column('función', sa.String(
                        length=120), nullable=False),
                    sa.ForeignKeyConstraint(['id_empresa'], ['empresa.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id_empleado')
                    )
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('direccion', sa.String(length=120), nullable=False))
        batch_op.alter_column('fundacion',
                              existing_type=sa.VARCHAR(),
                              type_=sa.Integer(),
                              existing_nullable=False,
                              postgresql_using='fundacion::integer')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.Boolean(), nullable=False))
        batch_op.drop_column('activo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.BOOLEAN(),
                            autoincrement=False, nullable=False))
        batch_op.drop_column('estado')

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('fundacion',
                              existing_type=sa.Integer(),
                              type_=sa.VARCHAR(),
                              existing_nullable=False)
        batch_op.drop_column('direccion')

    op.drop_table('programador')
    op.drop_table('administrador')
    # ### end Alembic commands ###
