"""empty message

Revision ID: b0cb8001cc39
Revises: a5cffa318ac2
Create Date: 2026-07-07 19:24:21.490611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0cb8001cc39'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('fundacion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('biografia', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint(None, ['usuario'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('biografia')
        batch_op.drop_column('usuario')

    op.drop_table('empresa')
    # ### end Alembic commands ###
