"""empty message

Revision ID: bb511e022776
Revises: baef223dfe60
Create Date: 2026-07-08 15:00:38.614742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb511e022776'
down_revision = 'baef223dfe60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_favoritos',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('publicacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['publicacion_id'], ['publicacion.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'publicacion_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tabla_favoritos')
    # ### end Alembic commands ###
